### PR TITLE
Update for files

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
Added an update route for the files which can be used in the codeeditor for updating contents of text files

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN This one is ready to be merged 👍

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN pls merge the second commit. Don't merge the first one

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN  please merge this too

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Could u update the readme with procedure to run the backend server too. thnaks.

**Comment by ankushbhardwxj** [comment]
its already updated right? We use `npm run dev` that starts both server and client. 
Mongodb should be installed & running.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
can you make a seperate pr with only update router commit cause i dont have time to rebase. Thanks!

**Comment by ankushbhardwxj** [comment]
sure !

**Pull request closed without merging**
