### PR TITLE
fixed taskbar time issue

### LINKED ISSUE #10: Fix Time And Date
1) Replace the clock app with cool clock.
2)Date and time not properly aligned( Microsoft Edge Dev) not sure about chrome, But time and date placements need changes.

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
Partly resolves #10 
Fixed the CSS of time and date on taskbar.

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN pls review :)

**Comment by ankushbhardwxj** [comment]
taskbar
I hope its fine to be placed like this

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Could you check in devices with smaller screen - open in your phone and see if its working,resize the windows and see the effects.

**Comment by ankushbhardwxj** [comment]
Done. I believe it will work fine for all orientations now.

**Comment by ankingcodes** [comment]
I think we can merge this. Let me know for changes. 🎉

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN please review and merge 👍

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
> @RAJAGOPALAN-GANGADHARAN please review and merge 👍

Done and added points Have Fun.

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN I think you added points for only one PR. But I made 2.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Ok added for one more too.

**Comment by ankushbhardwxj** [comment]
Thank you

**Pull request merged**
