### PR TITLE
Changed basic frontend of calculator app and Updated keypress events

### PR DESCRIPTION
**Pull request by Vishalghyv**
Background of Result screen and Display of history changed

### CODE REVIEW

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Could you post a gif of the result thanks.

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
@ankingcodes could you test this or and let me know if it’s ok. Thanks

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
I think its great! Added points... welcome aboard

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Im not able to find ur handle in the leaderboard page. Please let me know ur nwoc handle so that I can add points.

**Comment by Vishalghyv** [comment]
@Vishalghyv should be my handle but i still will tag you in NJACK gitter
chat

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Added ur handle and points check now....

**Pull request merged**
