### PR TITLE
created TodoApp

### LINKED ISSUE #19: ToDo App
A ToDo app is an essential app in every OS. We require a ToDo App capable of doing CRUD operations.

### PR DESCRIPTION
**Pull request by ankushbhardwxj**
fixed #19 
I have created a Todoapp capable of performing CRUD operations.
JS-OS-GoogleChrome2019-12-2019-5

### CODE REVIEW

**Comment by ankushbhardwxj** [comment]
@RAJAGOPALAN-GANGADHARAN please review & merge 👍

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
GIF Please

**Comment by ankushbhardwxj** [comment]
already given above 👀

**Comment by RAJAGOPALAN-GANGADHARAN** [comment]
Awesome it is Sick Dude 👍 . Points added have fun.

**Pull request merged**
